# ===========================================
# ORION GATEWAY SERVICE - Simplified Configuration
# Uses centralized environment variables from .env files
# ===========================================

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${GATEWAY_NAME:orion-gateway}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    # Disable Consul Discovery
    consul:
      enabled: false
      discovery:
        enabled: false

    # Load balancer configuration
    loadbalancer:
      configurations:
        default:
          health-check:
            enabled: true
            interval: 30s

    gateway:
      # Gateway route configuration with centralized URLs
      routes:
        # User management routes
        - id: user-service-lb
          uri: ${ORION_USER_URL}
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users(?<segment>.*), /service/user$\{segment}
            - name: CircuitBreaker
              args:
                name: user-service-cb
                fallbackUri: forward:/fallback/user
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,GATEWAY_TIMEOUT
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: role-service-lb
          uri: ${ORION_USER_URL}
          predicates:
            - Path=/api/roles/**
          filters:
            - RewritePath=/api/roles(?<segment>.*), /service/role$\{segment}
            - name: CircuitBreaker
              args:
                name: role-service-cb
                fallbackUri: forward:/fallback/user

        # Authentication routes
        - id: auth-service-lb
          uri: ${ORION_AUTH_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth(?<segment>.*), /authenticate$\{segment}
            - name: CircuitBreaker
              args:
                name: auth-service-cb
                fallbackUri: forward:/fallback/auth
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,GATEWAY_TIMEOUT

        # Program management routes
        - id: program-service-lb
          uri: ${ORION_PROGRAM_URL}
          predicates:
            - Path=/api/programs/**
          filters:
            - RewritePath=/api/programs(?<segment>.*), /service/program$\{segment}
            - name: CircuitBreaker
              args:
                name: program-service-cb
                fallbackUri: forward:/fallback/program

        # Document management routes
        - id: document-service-lb
          uri: ${ORION_DOCUMENT_URL}
          predicates:
            - Path=/api/documents/**
          filters:
            - RewritePath=/api/documents(?<segment>.*), /service/document$\{segment}
            - name: CircuitBreaker
              args:
                name: document-service-cb
                fallbackUri: forward:/fallback/document

        # Drive service routes
        - id: drive-service-lb
          uri: ${ORION_DRIVE_URL}
          predicates:
            - Path=/api/drive/**
          filters:
            - RewritePath=/api/drive(?<segment>.*), /service/drive$\{segment}
            - name: CircuitBreaker
              args:
                name: drive-service-cb
                fallbackUri: forward:/fallback/drive

        # Health check route
        - id: health-check
          uri: http://localhost:${SERVER_PORT:8080}
          predicates:
            - Path=/health
          filters:
            - SetPath=/actuator/health

      # CORS Configuration - Uses centralized variables
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "https://*.vercel.app"
              - "https://*.netlify.app"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      # Default filters
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Gateway-Service, ${GATEWAY_NAME:orion-gateway}
        - AddResponseHeader=X-Gateway-Version, 1.0.0
        - AddResponseHeader=X-Load-Balancer, enabled

# Circuit Breaker Configuration - Uses centralized variables
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: ${SERVICE_MIN_CALLS:5}
        failure-rate-threshold: ${SERVICE_FAILURE_RATE:50}
        wait-duration-in-open-state: ${SERVICE_CIRCUIT_WAIT:30s}
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      user-service-cb:
        base-config: default
      auth-service-cb:
        base-config: default
      program-service-cb:
        base-config: default
      document-service-cb:
        base-config: default
      drive-service-cb:
        base-config: default

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,env,circuitbreakers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Application Info - Uses centralized variables
info:
  app:
    name: ${GATEWAY_NAME:Orion Gateway}
    description: Load Balanced Gateway for Orion Microservices
    version: 1.0.0
    features:
      - Load Balancing
      - Circuit Breaker
      - Retry Logic
      - Health Checks

# Logging Configuration - Uses centralized variables
logging:
  level:
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:INFO}
    org.springframework.cloud.loadbalancer: ${LOG_LEVEL_GATEWAY:DEBUG}
    org.springframework.web.cors: ${LOG_LEVEL_WEB:DEBUG}
    com.unibague.gradework: ${LOG_LEVEL:DEBUG}
    org.springframework.cloud.circuitbreaker: ${LOG_LEVEL_GATEWAY:INFO}
    root: ${LOGGING_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

---
# ===========================================
# DEVELOPMENT PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: dev

# Development-specific overrides if needed
logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG

---
# ===========================================
# DOCKER PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: docker

# All Docker configuration comes from environment variables

---
# ===========================================
# PRODUCTION PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: prod

# Production-specific settings
logging:
  level:
    root: WARN
    com.unibague.gradework: INFO
    org.springframework.cloud.loadbalancer: INFO