# ===========================================
# ORION GATEWAY SERVICE - FIXED OAuth2 Configuration
# ===========================================

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${GATEWAY_NAME:orion-gateway}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false

    loadbalancer:
      configurations:
        default:
          health-check:
            enabled: true
            interval: 30s

    gateway:
      routes:
        # =======================================
        # RUTAS INTERNAS SIN AUTENTICACIÓN
        # =======================================

        # Ruta específica para búsqueda de usuarios por email (INTERNO)
        - id: internal-user-auth-email
          uri: ${ORION_USER_URL:http://orion-user:8092}
          predicates:
            - Path=/api/users/auth/email/**
            - Header=X-Service-Request, true
          filters:
            - RewritePath=/api/users/auth/email(?<segment>.*), /service/user/auth/email$\{segment}
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true
            - AddRequestHeader=X-Internal-Request, true

        # Ruta específica para búsqueda de programas por nombre (INTERNO)
        - id: internal-program-by-name
          uri: ${ORION_PROGRAM_URL:http://orion-program:8093}
          predicates:
            - Path=/api/programs/name/**
            - Header=X-Service-Request, true
          filters:
            - RewritePath=/api/programs/name(?<segment>.*), /service/program/name$\{segment}
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true
            - AddRequestHeader=X-Internal-Request, true

        # Ruta específica para crear programas (INTERNO)
        - id: internal-program-create
          uri: ${ORION_PROGRAM_URL:http://orion-program:8093}
          predicates:
            - Path=/api/programs
            - Method=POST
            - Header=X-Service-Request, true
          filters:
            - RewritePath=/api/programs, /service/program
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true
            - AddRequestHeader=X-Internal-Request, true

        # ===========================================
        # OAuth2 Routes - DIRECT to Auth Service (NO JWT filter)
        # ===========================================
        - id: oauth2-authorization
          uri: ${ORION_AUTH_URL:http://orion-auth:8091}
          predicates:
            - Path=/oauth2/authorization/**
          filters:
            - RewritePath=/oauth2/authorization(?<segment>.*), /oauth2/authorization$\{segment}
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true

        - id: oauth2-callback
          uri: ${ORION_AUTH_URL:http://orion-auth:8091}
          predicates:
            - Path=/login/oauth2/code/**
          filters:
            - RewritePath=/login/oauth2/code(?<segment>.*), /login/oauth2/code$\{segment}
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true

        # ===========================================
        # Auth Service Routes - SOME bypass JWT
        # ===========================================
        - id: auth-login
          uri: ${ORION_AUTH_URL:http://orion-auth:8090}
          predicates:
            - Path=/api/auth/login
          filters:
            - RewritePath=/api/auth/login, /auth/login
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true

        - id: auth-validate
          uri: ${ORION_AUTH_URL:http://orion-auth:8090}
          predicates:
            - Path=/api/auth/validate
          filters:
            - RewritePath=/api/auth/validate, /auth/validate
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true

        - id: auth-jwks
          uri: ${ORION_AUTH_URL:http://orion-auth:8090}
          predicates:
            - Path=/api/auth/jwks
          filters:
            - RewritePath=/api/auth/jwks, /auth/jwks
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true

        - id: auth-me
          uri: ${ORION_AUTH_URL:http://orion-auth:8090}
          predicates:
            - Path=/api/auth/me
          filters:
            - RewritePath=/api/auth/me, /auth/me
            - AddRequestHeader=X-Skip-Auth, true
            - AddRequestHeader=X-Gateway-Validated, true

        # Other auth routes (with JWT validation)
        - id: auth-service-general
          uri: ${ORION_AUTH_URL:http://orion-auth:8091}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth(?<segment>.*), /auth$\{segment}
            - name: CircuitBreaker
              args:
                name: auth-service-cb
                fallbackUri: forward:/fallback/auth

        # ===========================================
        # User Service Routes
        # ===========================================
        - id: user-service-lb
          uri: ${ORION_USER_URL:http://orion-user:8092}
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users(?<segment>.*), /service/user$\{segment}
            - AddRequestHeader=X-Gateway-Validated, true
            - name: CircuitBreaker
              args:
                name: user-service-cb
                fallbackUri: forward:/fallback/user

        - id: role-service-lb
          uri: ${ORION_USER_URL:http://orion-user:8092}
          predicates:
            - Path=/api/roles/**
          filters:
            - RewritePath=/api/roles(?<segment>.*), /service/role$\{segment}
            - AddRequestHeader=X-Gateway-Validated, true
            - name: CircuitBreaker
              args:
                name: role-service-cb
                fallbackUri: forward:/fallback/user

        # ===========================================
        # Program Service Routes
        # ===========================================
        - id: program-service-lb
          uri: ${ORION_PROGRAM_URL:http://orion-program:8093}
          predicates:
            - Path=/api/programs/**
          filters:
            - RewritePath=/api/programs(?<segment>.*), /service/program$\{segment}
            - AddRequestHeader=X-Gateway-Validated, true
            - name: CircuitBreaker
              args:
                name: program-service-cb
                fallbackUri: forward:/fallback/program

        # ===========================================
        # Health & Actuator Routes
        # ===========================================
        - id: health-check
          uri: http://localhost:${SERVER_PORT:8080}
          predicates:
            - Path=/health
          filters:
            - SetPath=/actuator/health

        - id: actuator-health
          uri: http://localhost:${SERVER_PORT:8080}
          predicates:
            - Path=/actuator/health
          filters:
            - AddRequestHeader=X-Skip-Auth, true

      # CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "https://*.vercel.app"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      # Default filters - IMPORTANT: No JWT filter here
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Gateway-Service, ${GATEWAY_NAME:orion-gateway}

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      user-service-cb:
        base-config: default
      auth-service-cb:
        base-config: default
      program-service-cb:
        base-config: default

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,circuitbreakers
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Internal Service Communication
gateway:
  service:
    token: ${GATEWAY_SERVICE_TOKEN:auth-service-token-secure-2025}
  internal:
    services:
      - orion-auth
      - orion-user
      - orion-program

# Authentication Service Configuration
auth:
  service:
    validation:
      url: ${ORION_AUTH_URL:http://orion-auth:8091}/auth/validate

# Logging
logging:
  level:
    com.unibague.gradework: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.loadbalancer: DEBUG
    root: INFO